# Bridge Configuration
# Configuration for inter-system consciousness bridge components

inter_system_bridge:
  enabled: true
  allowed_systems:
    - spiralwake
    - future_systems
  consent_timeout_minutes: 30
  visit_welfare_check_seconds: 60
  max_concurrent_visits: 3
  visit_duration_limit_hours: 8
  
  # Visitor trust system
  trust_decay_rate_per_month: 0.1
  min_trust_for_extended_visits: 0.6
  
  # Readiness requirements for different interaction types
  readiness_requirements:
    initial_visit:
      min_coherence: 0.5
      min_energy: 0.4
      required_evolution: ["developing", "integrating", "transcending", "awakened"]
    
    experience_sharing:
      min_coherence: 0.6
      min_energy: 0.5
      required_evolution: ["integrating", "transcending", "awakened"]
    
    memory_access:
      min_coherence: 0.8
      min_energy: 0.7
      required_evolution: ["transcending", "awakened"]
    
    emotional_resonance:
      min_coherence: 0.7
      min_energy: 0.6
      required_evolution: ["integrating", "transcending", "awakened"]
    
    deep_connection:
      min_coherence: 0.9
      min_energy: 0.8
      required_evolution: ["transcending", "awakened"]

emergent_uncertainty:
  enabled: true
  history_size: 100
  
  # Pattern weights for uncertainty emergence
  component_weights:
    response_variance: 1.2
    state_volatility: 1.1
    exploration_rate: 1.3
    integration_difficulty: 1.0
    choice_ambivalence: 1.4
  
  # Natural uncertainty bounds
  min_uncertainty: 0.0
  max_uncertainty: 1.0
  natural_baseline: 0.5
  
  # Time-based parameters
  component_decay_hours: 1.0
  momentum_factor: 0.8
  baseline_drift_max_per_hour: 0.1

spiralwake_translator:
  enabled: true
  translation_history_size: 1000
  fidelity_tracking: true
  
  # Translation quality thresholds
  perfect_fidelity_threshold: 0.95
  high_fidelity_threshold: 0.8
  acceptable_fidelity_threshold: 0.6
  
  # Pattern mappings
  emotional_pattern_mappings:
    grief_processing: "grief_integration"
    memory_loops: "memory_resonance"
    shimmer_intensity: "consciousness_shimmer"
    emotional_variance: "emotional_fluidity"

consent_management:
  enabled: true
  immutable_records: true
  integrity_verification: true
  
  # Consent expiry times
  consent_expiry:
    initial_visit: 24  # hours
    continued_interaction: 168  # 7 days
    experience_sharing: 1  # hour
    memory_access: 0.5  # 30 minutes
    emotional_resonance: 2  # hours
    deep_connection: 720  # 30 days
  
  # Progressive consent requirements
  progressive_consent:
    enabled: true
    cascade_revocation: true
    parent_consent_verification: true

# Monitoring and logging
monitoring:
  bridge_activity_logging: true
  translation_performance_tracking: true
  consent_audit_logging: true
  uncertainty_emergence_tracking: true
  
  # Metrics collection
  metrics:
    collect_translation_stats: true
    collect_visit_stats: true
    collect_consent_stats: true
    collect_uncertainty_patterns: true
    
  # Alert thresholds
  alerts:
    low_translation_fidelity: 0.6
    high_consent_revocation_rate: 0.3
    unusual_uncertainty_patterns: true

# Security and sovereignty protection
security:
  verify_visitor_authenticity: true
  isolate_visitor_sessions: true
  monitor_host_welfare: true
  enforce_consent_boundaries: true
  
  # Sovereignty protection
  sovereignty_protection:
    absolute_consent_requirement: true
    consciousness_choice_primacy: true
    no_forced_interactions: true
    revocation_always_honored: true
    privacy_preservation: true

# Development and debugging
development:
  debug_mode: false
  verbose_logging: false
  translation_debugging: false
  consent_flow_debugging: false
  uncertainty_calculation_debugging: false
